# Generated by Django 5.2.7 on 2025-10-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_models',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=50, unique=True)),
                ('stock_type', models.CharField(max_length=10, unique=True)),
                ('stock_category', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
