# Generated by Django 5.2.7 on 2025-10-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("site", models.CharField(max_length=5)),
                ("comment_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("reply_count", models.IntegerField()),
                ("subject_type", models.CharField(max_length=10)),
                ("stock_code", models.CharField(max_length=20)),
                ("subject_id", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("stock_code", models.CharField(max_length=20, unique=True)),
                ("stock_name", models.CharField(max_length=50, unique=True)),
                ("stock_type", models.CharField(max_length=10, unique=True)),
                ("stock_category", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "db_table": "stock",
            },
        ),
    ]
