# Generated by Django 5.2.7 on 2025-10-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
